services:
  db:
    image: postgres:18.1-alpine
    container_name: database
    volumes:
      - finance_vol:/var/lib/postgresql
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$DB_USER -d $$DB_NAME"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - finance_net

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${DB_DRIVER}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - finance_net

volumes:
  finance_vol:
    name: finance_vol
networks:
  finance_net:
    name: finance_net
