spring:
  application:
    name: financetrecker
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/finance_db
    password: Thread.currentThread()
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: validate
server:
  servlet:
    context-path: /
  port: 8080
jwt:
  secret: 452f6f4d306b66314f346b7a69514e4b506b325254336c584a5647504369426d
  expiration: 900000